apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: svt-go-operator.v0.0.2
spec:
  version: 0.0.2
  displayName: SVT-GO Application
  provider:
    name: RH SVT
    url: www.redhat.com
  maturity: alpha
  maintainers:
    - email: guy@redhat.com
      name: Some Guy
  labels:
    olm-owner-enterprise-app: svt-go-operator
    olm-status-descriptors: svt-go-operator.v0.0.2
  description: SVT Tool in GoLang
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: svt-go-operator
        rules:
        - apiGroups:
          - app.example.com
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - "*"
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - "get"
      deployments:
      - name: svt-go-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: svt-go-operator
          template:
            metadata:
              labels:
                app: svt-go-operator
            spec:
              containers:
                - name: svt-go-operator-olm-owned
                  image: quay.io/hongkailiu/h-svt-go-operator:v0.0.2
                  imagePullPolicy: Always
                  env:
                  - name: MY_POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: WATCH_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: MY_POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: svt-go-operator
              serviceAccount: svt-go-operator
  customresourcedefinitions:
    owned:
      - description: Represents a cluster of SVTO-GO apps
        displayName: SVTO-GO App
        kind: SVTGo
        name: svtgos.app.example.com
        version: v1alpha1
        resources:
          - kind: DeploymentConfig
            version: apps.openshift.io/v1
          - kind: Route
            version: route.openshift.io/v1
          - kind: ReplicaSet
            version: v1beta2
          - kind: Pod
            version: v1
          - kind: Service
            version: v1
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: replicaCount
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
